### ISSUE TITLE
Ask questions everyone

### ISSUE THREAD

**Issue by DlgzRogelio** [DlgzRogelio/Project-1#8]

**Comment by ca2los** [comment]
Hello Team, 
After all the testing I've doing with **"The Movie Database"** I can tell you I see some challenges about the API:
____
#### Is it possible to mix or join multiple parameters inside one URL?
Yes, I tried to mix the "name of the actress/actor" with  "rated" and all I got were _error messages._ We have multiple options, but the API doesn't includes an option for custom queries/URLS. It seems like our alternatives are limited. **Am I missing something?** Plz tell me if you find a solution.

https://developers.themoviedb.org/3/search/multi-search
____

cc @DlgzRogelio @ian-dot @ltrevino

**Comment by ltrevino** [comment]
The team has decided to implement the TMDB api with people endpoint that does not require mixed queries.
